use_frameworks!

platform :ios, '9.0'

target 'SKNetworking_Example' do
  pod 'SKNetworking', :path => '../'

  target 'SKNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
